# PostgreSQL install, all based on the official manual.

- name: Create the file repository configuration.
  command: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  become: yes

- name: Import the repository signing key.
  apt_key: 
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: yes

- name: Update the package lists.
  apt:
    update_cache: yes
  become: yes

- name: Install the latest version of PostgreSQL.
  apt:
    name: postgresql
    state: present
  become: yes

- name: Create the DB.
  command: su postgres -c 'createdb {{ dbname }}'
  become: yes
